name: releaser

on:
  push:
    tags: ['v*']

jobs:
  no-bump-releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Github Releaser
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
